ALTER TABLE posts ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE bios ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE posts ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE bios ALTER COLUMN user_id DROP DEFAULT;
