// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package postgres

import (
	"database/sql"
	"time"
)

type Bio struct {
	ID     int64
	UserID int64
	Bio    string
}

type Post struct {
	ID          int64
	UserID      int64
	CreateAt    time.Time
	Title       string
	Description sql.NullString
	Content     sql.NullString
}

type User struct {
	ID       int64
	Name     string
	Password string
	ImgUrl   sql.NullString
}
